preload = ~/.config/hypr/wallpapers/space.jpg
preload = ~/.config/hypr/wallpapers/1920x1080-dark-archlinux.png
#wallpaper = , ~/.config/hypr/wallpapers/space.jpg
wallpaper = , ~/.config/hypr/wallpapers/1920x1080-dark-archlinux.png
